FROM dataman

RUN apt-get update && \
    apt-get install -y software-properties-common && \
    add-apt-repository ppa:cwchien/gradle && \
    apt-get update && \
    apt-get install -y gradle openjdk-7-jdk gcc g++ make curl
# aaaa
